base/urls.py
from atexit import register
from . import views
from django.urls import path


app_name = 'base'
urlpatterns = [
    # ex: localhots:8000/base/
    path("", view=views.home, name='home'),
    # ex: /base/room/1
    path('room/<str:pk>/', view=views.room, name='room'),
    # ex: /base/create_room
    path('create-room/', view=views.create_room, name='create-room'),
    # ex: /base/update-roon/1
    path('update-room/<str:pk>', view=views.updateRoom, name='update-room'),
    # ex: /base/delete-roon/1
    path('delete-room/<str:pk>', view=views.deleteRoom, name='delete-room'),
    # ex: base/login
    path('login/', view=views.loginPage, name='login'),
    # ex: base/logout
    path('logout/', view=views.logoutUser, name='logout'),
    # ex: base/register
    path('register/', view=views.registerPage, name='register'),
    # ex: base/delete_message
    path('delete-message/<str:pk>', view=views.delete_message, name='delete-message'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('base/', include('base.urls')),
]

base/models.py
# import libraries and components
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    
    def __str__(self) -> str:
        return self.name

class Room(models.Model):
    # "models.SET_NULL" will not let the child be deleted upon parent deletion
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=250)
    description = models.TextField(max_length=1000, null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    participants = models.ManyToManyField(User, 
                                            related_name='participants',
                                            blank=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self) -> str:
        return self.name

class Message(models.Model):
    # Cascade will 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField() # This is the message
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    # user

    def __str__(self) -> str:
        return self.body
    
    

base/forms.py
# imports 
from dataclasses import fields
from django.forms import ModelForm
from .models import Room

# Form Calculations 
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'

base/views.py
# imports 
from .forms import RoomForm
from django.db.models import Q
from django.contrib import messages
from .models import Message, Room, Topic
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import HttpResponse, redirect, render, get_object_or_404

# ------------------------------------------------------------------------ #
# Create your views here.
def home(request):
    # Get quesry set value from the request once user has clicked on any topic name
    # q = request.GET.get('q') if request.GET.get('q') != None else ''
    if request.GET.get('q') != None:
        q = request.GET.get('q')
    else:
        q = ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) | 
        Q(name__icontains=q) |
        Q(description__icontains=q))
    # Calculate the room count 
    room_count = rooms.count()

    # Let's browser all the topics
    topics = Topic.objects.all()[:10]
    context = {
        'rooms': rooms,
        'topics': topics,
        'room_count': room_count
    }
    return render(request, 'base/home.html', context)

def room(request, pk):
    room = get_object_or_404(Room, pk=int(pk))
    # Let's get the messages 
    room_messages = room.message_set.all().order_by('-created')
    # Let's get the participants
    participants = room.participants.all()
    # if post request comes from the from
    if request.method == 'POST':
        # Create new mesage 
        msg = Message.objects.create(
            user=request.user,
            room=room,
            body=request.POST.get('body')
        )
        room.participants.add(request.user)
        msg.save()
        # Redirect the user
        return redirect('base:room', pk=room.id)

    context = {
        'room': room,
        'room_messages': room_messages,
        'participants': participants
    }
    return render(request, 'base/room.html', context)
# ------------------------------------------------------------------------ #
# Function for creating the room
@login_required(login_url='base:login')
def create_room(request):
    # Room forms will be used here
    form = RoomForm()
    if request.method == 'POST':
        f = RoomForm(request.POST)
        if f.is_valid():
            # Save the model
            f.save()
            # After saving the model, 
            return redirect('/base/')
            
    # Provide the context
    context = {
        'form': form
    }
    return render(request, 'base/room_form.html', context)
# ------------------------------------------------------------------------ #
# Creaet view for updating the room 
@login_required(login_url='base:login')
def updateRoom(request, pk):
    room = Room.objects.get(id=pk)
    
    # Only the creator of room can delete the room
    if request.user != room.host:
        return HttpResponse('You cant change the room content')

    # Create the form object 
    form = RoomForm(instance=room) # This line will fill the form with data that we have in our database and it belong the object we are showing
    if request.method == "POST":
        f = RoomForm(request.POST, instance=room)
        if f.is_valid():
            # Save the form and redirect it to the main page
            f.save()
            return redirect('/base/')
    context = {
        'form': form
    }
    return render(request, 'base/room_form.html', context)
# ------------------------------------------------------------------------ #
@login_required(login_url='base:login')
def deleteRoom(request, pk):
    room = Room.objects.get(id=int(pk))

    # Only the creator of room can delete the room
    if request.user != room.host:
        return HttpResponse('You cant change the room content')

    if request.method == "POST":
        room.delete()
        return redirect('/base/')
    context = {
        'obj': room
    }
    return render(request, 'base/delete.html', context)
# ------------------------------------------------------------------------ #
def loginPage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('/base/')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        print(f'username is : {username}, and size is : {len(username)}, password is : {password}')
        # Use try catch block 
        try:
            user = User.objects.get(username=username)
            user = authenticate(request,
                    username=username,
                    password=password)
            if user is not None:
                login(request, user)
                # Redirect the user 
                return redirect('/base/')
            else:
                messages.error(request, 'user credential are not correct')
        except:
            # Throw the error message that user does not exit
            messages.error(request, 'user does not exist')
    context = {
        'page': page
    }
    return render(request, 'base/login_register.html', context)
# ------------------------------------------------------------------------ #
def logoutUser(request):
    logout(request) # This will delete the session token for the user
    return redirect('/base/')
# ------------------------------------------------------------------------ #
def registerPage(request):
    form = UserCreationForm()
    # Let's process the form
    if request.method == 'POST':
        f = UserCreationForm(request.POST)
        if f.is_valid():
            # save the form and freeze the user
            user = f.save(commit=False)
            user.username = user.username.lower()
            user.save()
            # login the user
            login(request, user=user)
            # redirect the user
            return redirect('/base/')
        else:
            messages.error(request, 'Something went wrong, please try again')
    context = {
        'form': form
    }
    return render(request, 'base/login_register.html', context)
# ------------------------------------------------------------------------ #
@login_required(login_url='base:login')
def delete_message(request, pk):
    message = Message.objects.get(id=int(pk))
    if request.user != message.user:
        return HttpResponse('you are not allowed !')
    if request.method == 'POST':
        message.delete()
        return redirect('/base/')
    context = {
        'obj': message
    }
    return render(request, 'base/delete.html', context)
# ------------------------------------------------------------------------ #

base/templates/base/delete.html
<!-- Let's extends the delete funionality-->
{% extends 'base/main.html' %}

<!-- Populate the block -->
{% block content %}
    <form action="" method="POST">
        <!-- csrf_token must be added for all the forms -->
        {% csrf_token %}
        <p>
            Are you sure you want to delete this "{{ obj  }}"
        </p>
        <!-- Send user back to the link they come from -->
        <a href="{{request.META.HTTP_REFRER}}">Go Back</a>
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}

base/templates/base/home.html
<!-- Extends the main page -->
{% extends 'base/main.html' %}

<!-- Extending templates is a lot more cleaner approach -->
<!-- Starts content block -->
{% block content %}

    <div class="home-container">
        <!-- Adding sidebar -->
        <div>
            <!-- Sidebar -->
            <h3>
                Browse Topics
            </h3>
            <hr>
            <!-- Get back to all pages -->
            <div>
                <a href="{% url 'base:home' %}">All</a>
            </div>
            <!-- Let's browse through the topics -->
            {% if topics %}
                {% for topic in topics %}
                    <div>
                        <a href="{% url 'base:home' %}?q={{topic.name}}">{{ topic.name }}</a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        
        <!-- Show list of rooms -->
        <div>
            <h5>{{room_count}} rooms available</h5>
            <!-- Create room link -->
            <a href="{% url 'base:create-room' %}">Create Room</a>    
            <hr>
            {% if rooms %}
            <!-- For loop over all of the  -->
                {% for room in rooms %}
                    <div>
                        <a href="{% url 'base:room' room.id %}"> {{ room.name }} </a>
                        <br>
                        <span>@{{ room.host.username }}</span>
                        <small>{{ room.topic.name }}</small>
                        <br>
                        <small>
                            Topic : {{ room.topic.name }}
                            <!-- If user is not the host, edit and delete button will not be shown -->
                            {% if request.user == room.host %}
                                <em>
                                    <a href="{% url 'base:update-room' room.id %}">Edit</a>
                                </em>
                                <!-- Let's enter the delete button -->
                                <a href="{% url 'base:delete-room' room.id %}">Delete</a>
                                <hr>
                            {% endif %}
                            
                        </small>
                    </div>
                {% endfor %}    
            {% else %}
                <h1>No Room has been added</h1>
            {% endif %}
        </div>

    </div>

{% endblock content %}

base/templates/base/login_register.html
{% extends 'base/main.html' %}

<!-- Extends the block -->
{% block content %}
    {% if page == 'login' %}
        <div>
            <!-- form for login -->
            <form action="" method="POST">
                {% csrf_token %}
                <label for="">Username</label>
                <input type="text" name="username" placeholder="Enter Username">
                <label for="">Password</label>
                <input type="password" name="password" placeholder="Enter password">
                <input type="submit" value="Login">
            </form>
            <p>haven't signed up yet?</p>
            <a href="{% url 'base:register' %}">Signup</a>
        </div>
    {% else %}
        <!-- For signup -->
        <div>
            <!-- form for registration or authentication -->
            <form action="" method="POST">
                {% csrf_token %}
                <!-- auto generate form field -->
                {{ form.as_p }}
                <input type="submit" value="Register">
            </form>
            <p>Already signed up </p>
            <a href="{% url 'base:login' %}">Login</a>
        </div>
    {% endif %}
{% endblock content %}

base/templates/base/main.html
{% load static %}
<link rel="stylesheet" href="{% static '/base/style.css' %}">
<!DOCTYPE html>
<html>
    <head lang="en">
        
        <!-- G Settings for web page -->
        <meta charset="urf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- Customized settin for our web page -->
        <title>StudyBud</title>
    
    </head>

    <body>
        
        <!-- Add Navbar for every page -->
        {% include 'base/navbar.html' %}
            <!-- Create blocks that will be inherited later on -->
            
        <!-- Messages -->
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if messsage.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        {% block content %} 
            <!-- This block is for content displaying -->
        {% endblock %}

    </body>

</html>

base/templates/base/navbar.html
<!DOCTYPE html>
<html lang="en">
    <nav>
        <a href="{% url 'base:home' %}">Home</a>
    </nav>
    <hr>
    <!-- Let's add search bar -->
    <form action="{% url 'base:home' %}" method="GET">
        <input type="text" name="q" placeholder="Search Rooms...">
    </form>

    <!-- Displaying the logout button -->
    {% if request.user.is_authenticated %}
        <!-- Display the logout button -->
        <p>Hello : {{ request.user }}</p>
        <a href="{% url 'base:logout' %}">Logout</a>    
    {% else %}
        <a href="{% url 'base:login' %}">Login</a>
    {% endif %}
    <!--  
        
    -->
</html>

base/templates/base/room.html
{% extends 'base/main.html' %}

<!-- Let's extends the block -->
{% block content %}

    <div class="room-container">
        <div>
            
            <!-- Let's show the name of the room and further details -->
            <h1>{{ room.name }}</h1>
            
            <!-- Let's add the room description -->
            {% if room.description %}
                <p>Description: {{ room.description }}</p>
            {% endif %}
            
            <!-- Adding div for commenst -->
            <div class="comment-wrapper">
                <h3>
                    Conversation
                </h3>
                <hr>
                <!-- Iterate over all the messages -->
                {% for message in room_messages %}
                    <div>
                        <!-- Only the owner can delete the comment -->
                        {% if request.user == message.user %}
                            <a href="{% url 'base:delete-message' message.id %}">Delete</a>
                        {% endif %}
                        
                        <small>@{{ message.user }}  {{ message.created|timesince }} ago</small>
                        <p>{{ message.body }}</p>
                    </div>
                {% endfor %} 

            </div>
            <!-- only authenticate user can enter message -->
            <!-- div for commentin -->
            {% if request.user.is_authenticated %}
                <div class="comment-form">
                    <form action="" method="POST">
                        {% csrf_token %}

                        <input type="text" name="body" placeholder="write your message here ...">
                    </form>
                </div>
            {% endif %}
        
        </div>
        <!-- Create div for participants -->
        <div>
            <h3>Participants</h3>
            <hr> <!-- This is a line break -->
            {% for user in participants %}
                <div>
                    <p>
                        @{{ user.username }}
                    </p>
                </div>
            {% endfor %}
        </div>
        
    </div>

{% endblock content %}

base/templates/base/room_form.html
{% extends 'base/main.html' %}

<!--make changes to the block -->
{% block content %}
    <div>
        <form action="" method="post">
            <!-- Add csrf token -->
            {% csrf_token %}
                <!-- Dsiplay the form -->
            {{ form.as_p }}
            <input type="submit" value="Submit">
        </form>
    </div>    
{% endblock content %}